# netlify.toml
[build]
  command = "npm run build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "20"
  SHEET_ID = "2PACX-...your-id-here..." # <-- set in the Netlify UI instead of committing if you prefer
  # SHEET_GID = "123456789"            # optional, if your sheet uses a non-default gid

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
