# netlify.toml

[build]
  command = "npm run build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "20"   # ✅ SHEET_ID/SHEET_URL come from Netlify UI now

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
